### ISSUE TITLE
What's wrong when I see "Direct constraints on independent variables are not supported. Please make sure your constraint involves at least one decision variable."?

### ISSUE THREAD

**Issue by Y-Z-Chen** [oxfordcontrol/SOSTOOLS#19]
As the title (sorry for its length). The title is the problem I face when I try to run sosdemo1.m, sosdemo4.m, and sosdemo9.m with SOSTOOLS(v4.03) and MATLAB R2021a. I hope it can be solved within a week.

**Comment by djagt** [comment]
Hi, is it possible you are working with a slightly older version of SOSTOOLS? We recently (a few months ago) pushed an update to GitHub that should have resolved this issue, when I try running the demos on my system, I do not get any error. Could you try reinstalling the current latest codes from GitHub?

**Comment by Y-Z-Chen** [comment]
The problem is solved in the method you said. Thanks.
